package org.beta;

import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Map;

import org.magic.api.interfaces.abstracts.AbstractMagicSQLDAO;

public class OracleDbDAO extends AbstractMagicSQLDAO{

	@Override
	public Map<String, String> getDefaultAttributes() {
		return Map.of(SERVERPORT, "1521",
				   LOGIN, "user",
				   PASS, "mypass",
				   PARAMS, "",
				   "DUMP_PATH", "C:\\Program Files (x86)\\Mysql\\bin"
				);
	}
	@Override
	protected String getBoolean()
	{
		return "CHAR(1)";
	}
	
	@Override
	protected String getjdbcUrl() {
		return "jdbc:"+getjdbcnamedb()+"@"+getString("SERVERNAME")+":"+getString("SERVERPORT")+":"+getString("DB_NAME");
	}
	
	@Override
	public void backup(File dir) throws SQLException, IOException {
		// TODO Auto-generated method stub
	}
	
	
	@Override
	public void createIndex(Statement stat) throws SQLException {
		//TODO fix correct index query
	}
	
	
	@Override
	protected String notExistSyntaxt() {
		return " ";
	}
	
	@Override
	public String getName() {
		return "Oracle";
	}

	@Override
	protected String getAutoIncrementKeyWord() {
		return "NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY";
	}

	@Override
	protected String getjdbcnamedb() {
		return "oracle:thin:";
	}
	

	@Override
	protected String beanStorage() {
		return "CLOB";
	}

	@Override
	protected String longTextStorage() {
		return "CLOB";
	}

	@Override
	protected String createListStockSQL() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected String getdbSizeQuery() {
		return "";
	}

}
