package org.magic.api.dao.impl;

import java.io.File;
import java.io.IOException;
import java.sql.SQLException;

import org.magic.api.interfaces.abstracts.AbstractMagicSQLDAO;
import org.magic.services.MTGControler;

public class OracleDbDAO extends AbstractMagicSQLDAO{

	
	@Override
	public void initDefault() {
		setProperty(SERVERPORT, "1521");
		setProperty(LOGIN, "user");
		setProperty(PASS, "mypass");
		setProperty(PARAMS, "");
		setProperty("DUMP_PATH", "");
	}

	public static void main(String[] args) throws SQLException {
		MTGControler.getInstance();
		new OracleDbDAO().init();
	}
	
	@Override
	protected String getjdbcUrl() {
		return "jdbc:"+getjdbcnamedb()+"@"+getString("SERVERNAME")+":"+getString("SERVERPORT")+":"+getString("DB_NAME");
	}
	
	@Override
	public void backup(File dir) throws SQLException, IOException {
		// TODO Auto-generated method stub
		
	}
	
	
	@Override
	protected String notExistSyntaxt() {
		return " ";
	}
	
	@Override
	public String getName() {
		return "Oracle";
	}

	@Override
	protected String getAutoIncrementKeyWord() {
		return "NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY";
	}

	@Override
	protected String getjdbcnamedb() {
		return "oracle:thin:";
	}
	

	@Override
	protected String beanStorage() {
		return "CLOB";
	}

	@Override
	protected String longTextStorage() {
		return "CLOB";
	}

	@Override
	protected String createListStockSQL() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	protected String getdbSizeQuery() {
		return "";
	}

}
